security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backenddb
    username: backend
    password: backend
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5432/backenddb
    user: backend
    password: backend
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0